# Generated by Django 3.1.2 on 2020-11-11 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zooapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name': 'семейство', 'verbose_name_plural': 'семейства'},
        ),
        migrations.AlterModelOptions(
            name='genus',
            options={'verbose_name': 'род', 'verbose_name_plural': 'род'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'место нахождения', 'verbose_name_plural': 'места нахождения'},
        ),
        migrations.AlterModelOptions(
            name='subspecies',
            options={'verbose_name': 'вид', 'verbose_name_plural': 'виды'},
        ),
        migrations.AlterModelOptions(
            name='typeofanimal',
            options={'verbose_name': 'отряд', 'verbose_name_plural': 'отряды'},
        ),
        migrations.AddField(
            model_name='animal',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zooapp.employee', verbose_name='Работник'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zooapp.typeofanimal', verbose_name='Отряд'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zooapp.place', verbose_name='Место нахождения'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='subspecies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zooapp.subspecies', verbose_name='Вид'),
        ),
    ]
