# Generated by Django 3.1.2 on 2020-11-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zooapp', '0002_auto_20201111_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='employee_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата закрепления'),
        ),
    ]
