# Generated by Django 3.1.2 on 2020-11-12 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zooapp', '0003_animal_employee_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='employee_date',
        ),
    ]
