# Generated by Django 3.1.2 on 2020-11-16 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zooapp', '0005_animal_employee_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='employee',
        ),
        migrations.CreateModel(
            name='AnimalToEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(verbose_name='Создан')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zooapp.animal', verbose_name='Животное')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zooapp.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'связь жив. с сотр.',
                'verbose_name_plural': 'связи жив. с сотр.',
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='employee',
            field=models.ManyToManyField(through='zooapp.AnimalToEmployee', to='zooapp.Employee', verbose_name='Работники'),
        ),
    ]
